---
title: "Base learner functionality"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Base learner functionality}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


<table>
  <tr>
    <th>Base-Learner</th>
    <th>Description</th>
    <th>Arguments</th>
  </tr>
  <tr>
    <td><code>BaselearnerPolynomial</code></td>
    <td>
      Fit polynomial base-learner. Note that this base-learner takes just the power of the selected feature. For instance, there is no linear part when using <code>degree = 2</code>.
    </td>
    <td>
      <dt><b>degree</b></dt> <dd>Polynomial degree of feature (default: 1)</dd>
      <dt><b>intercept</b></dt> <dd>Specification if an intercept column should be added (default: <code>TRUE</code>)</dd>
    </td>
  </tr>
  <tr>
    <td><code>BaselearnerPSpline</code></td>
    <td>Fit (penalized) spline regression base-learner.</td>
    <td>
      <dt><b>degree</b></dt> <dd>Polynomial degree of bases (default: 3)</dd>
      <dt><b>n_knots</b></dt> <dd>Number of inner knots (default: 20)</dd>
      <dt><b>penalty</b></dt> <dd>Penalty term to control the smoothness of the curve (default: 2)</dd>
      <dt><b>differences</b></dt> <dd>Number of penalized differences (default: 2)</dd>
    </td>
  </tr>
  <tr>
    <td><code>BaselearnerCustom</code></td>
    <td>Define a custom base-learner by using custom <code>R</code> functions.</td>
    <td>
      <dt><b>instantiate_fun</b></dt> <dd>Feature transformation, e.g., create spline bases.</dd>
      <dt><b>train_fun</b></dt> <dd>Function to train on the data generated by <code>instantiate_fun</code></dd>
      <dt><b>predict_fun</b></dt> <dd>Function to predict on the object returned by <code>train_fun</code></dd>
      <dt><b>param_fun</b></dt> <dd>Function to extract parameters as matrix from the object returned by <code>train_fun</code></dd>
    </td>
  </tr>
  <tr>
    <td><code>BaselearnerCustomCpp</code></td>
    <td>Define a custom base-learner by using custom <code>C++</code> functions.</td>
    <td>
      <dt><b>instantiate_ptr</b></dt> <dd>External pointer containing the reference to the <code>C++</code> feature transformation</dd>
      <dt><b>train_ptr</b></dt> <dd>Function to train on the data generated by <code>instantiate_ptr</code> which always returns the parameter as matrix</dd>
      <dt><b>predict_ptr</b></dt> <dd>Function to predict by using the parameter returned by <code>train_ptr</code></dd>
    </td>
  </tr>
</table>
