---
title: "Component-wise Boosting with compboost"
author: "Daniel Schalk"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
    css: compboost.css
bibliography: bibliography.bib
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

<hr>

`compboost` was designed to provide a component-wise boosting framework with
maximal flexibility. This document gives an introduction to the classes that 
must be set and where in the algorithm they are used. In this document we are
using the `C++` looking API which was generated using @eddelbuettel2017exposing
[Rcpp modules](https://cran.r-project.org/web/packages/Rcpp/vignettes/Rcpp-modules.pdf).
We will have a look at:

- Define the data and factory (baselearner generators) objects.
- Define the used loss and optimizer for modelling.
- Define different logger for tracking the algorithm.
- Run the algorithm and access the fitted values.
- Continue training of the algorithm and set the algorithm to a specific 
  iteration.

To get a deeper understanding about the functionality and how the classes are 
related see the [C++ documentation of the package](https://schalkdaniel.github.io/compboost/cpp_man/html/index.html).


## Data: Titanic Passenger Survival Data Set

## Data and Factories

## Loss and Optimizer

## Define Logger

- Verweis auf extending compboost mit einem auc logger

## Run the Algorithm

## Continue and Reposition the Training

## References