// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;


RcppExport SEXP _rcpp_module_boot_data_module();
RcppExport SEXP _rcpp_module_boot_baselearner_factory_module();
RcppExport SEXP _rcpp_module_boot_baselearner_list_module();
RcppExport SEXP _rcpp_module_boot_loss_module();
RcppExport SEXP _rcpp_module_boot_logger_module();
RcppExport SEXP _rcpp_module_boot_optimizer_module();
RcppExport SEXP _rcpp_module_boot_compboost_module();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_data_module", (DL_FUNC) &_rcpp_module_boot_data_module, 0},
    {"_rcpp_module_boot_baselearner_factory_module", (DL_FUNC) &_rcpp_module_boot_baselearner_factory_module, 0},
    {"_rcpp_module_boot_baselearner_list_module", (DL_FUNC) &_rcpp_module_boot_baselearner_list_module, 0},
    {"_rcpp_module_boot_loss_module", (DL_FUNC) &_rcpp_module_boot_loss_module, 0},
    {"_rcpp_module_boot_logger_module", (DL_FUNC) &_rcpp_module_boot_logger_module, 0},
    {"_rcpp_module_boot_optimizer_module", (DL_FUNC) &_rcpp_module_boot_optimizer_module, 0},
    {"_rcpp_module_boot_compboost_module", (DL_FUNC) &_rcpp_module_boot_compboost_module, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_compboost(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
